image: ubuntu:20.04

stages:
  - build

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -y git curl fakeroot zip unzip xz-utils build-essential rsync libncurses5 libxml2

build:
  stage: build
  script:
    - git clone --recursive --depth=1 https://github.com/theos/theos.git $HOME/theos
    - curl -LO https://github.com/sbingner/llvm-project/releases/latest/download/linux-ios-arm64e-clang-toolchain.tar.lzma
    - mkdir -p $HOME/theos/toolchain/linux/iphone
    - tar -xf linux-ios-arm64e-clang-toolchain.tar.lzma -C $HOME/theos/toolchain/linux/iphone --strip-components=1
    - curl -LO https://github.com/theos/sdks/archive/master.zip
    - unzip -q master.zip && mv sdks-master/* $HOME/theos/sdks/
    - export THEOS=$HOME/theos
    - make package FINALPACKAGE=1
    - mkdir -p Payload
    - cp -r .theos/_ Payload/
    - zip -r DDZHelper.ipa Payload
  artifacts:
    paths:
      - DDZHelper.ipa
      - packages/*.deb
